version: '3'

volumes:
    nodemodules:
    dist:
    cache:

services:
  test-ci:
    image: cypress-kit
    build:
        context: .
        args:
            NODE_VERSION: 14.7.0
            CHROME_VERSION: 84.0.4147.105
    container_name: cypress-test
    environment:
      - CYPRESS_baseUrl=https://example.cypress.io/
      - CYPRESS_video=false
    working_dir: /app
    volumes:
      - .:/app
    command:
      - "sh"
      - "-c"
      - "yarn && rm -rf test-results && mkdir –m777 test-results && yarn test-ci"
