version: '3'

volumes:
    nodemodules:

services:
  test-ci:
    image: cypress-testing
    build:
        context: .
        cache_from:
          - cypress-testing:latest
    container_name: cypress-test
    environment:
      - CYPRESS_baseUrl=https://example.cypress.io/
      - CYPRESS_video=false
    working_dir: /app
    volumes:
      - .:/app
      - nodemodules:/app/node_modules
    command:
      - "sh"
      - "-c"
      - "yarn && rm -rf test-results && mkdir -m 777 test-results && yarn test-ci"
